---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrsdeploy
spec:
  minReadySeconds: 0
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
      ver: "1.0"
  strategy:
    rollingUpdate:
      maxSurge: "33%"
      maxUnavailable: "33%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openmrs
        ver: "1.0"
    spec:
      containers:
        - name: openmrs
          image: ./openmrs:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
